server:
  port: 3034
  
spring:
  application:
    name: driver-service
  config:
     import: configserver:http://localhost:8888
         
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
